language: node_js
cache: 
  directories:
    - node_modules
script:
  - esca-scripts tset --serverless && esca-scripts deploy --serverless
notifications:
  email:
    on_failure: always
    on_success: never