service: salsify-cron-job
provider: 
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: ${opt:stage, 'development'}
  environment:
    NODE_ENV: ${opt:stage, 'development'}
    ENVDOTJS_KEY: ${env:ENVDOTJS_KEY}

functions:
  salsifyCron:
    handler: src/handler.salsifyCron
    events:
      - schedule: 
          rate: cron(*/5 * * * ? *)
          enabled: true

package:
  individually: true
  include:
    - env.js.enc
    - envdotjs-key

custom:
  serverless-offline:
    babelOptions:
      presets: ["es2015", "stage-3"]
      plugins: ["transform-runtime"]

plugins:
  - serverless-offline